# Generated by Django 3.0.2 on 2020-02-20 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subRefId', models.CharField(max_length=20)),
                ('salesOrderNo', models.CharField(max_length=20)),
                ('offerName', models.CharField(max_length=20)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
