# Generated by Django 3.0.2 on 2020-02-20 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sol', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comorder',
            name='createdDate',
        ),
    ]
