# Generated by Django 3.0.2 on 2020-03-03 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sol', '0002_remove_comorder_createddate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ComOrder',
            new_name='com_order_mapper',
        ),
    ]
