# Generated by Django 3.0.2 on 2020-03-03 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sol', '0003_auto_20200303_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='com_order_mapper',
            name='lineStatus',
            field=models.IntegerField(blank=True, default=32),
        ),
        migrations.AddField(
            model_name='com_order_mapper',
            name='subscriptionId',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='com_order_mapper',
            name='salesOrderNo',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='com_order_mapper',
            name='subRefId',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
