# Generated by Django 3.0.2 on 2020-03-03 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sol', '0005_com_order_mapper_requestedstartdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='com_order_mapper',
            name='requestedStartDate',
            field=models.DateField(default='1990-10-28'),
        ),
    ]
