# Generated by Django 3.0.2 on 2020-03-03 12:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sol', '0006_auto_20200303_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='com_order_mapper',
            name='creationDate',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 3, 17, 38, 21, 293817)),
        ),
        migrations.AddField(
            model_name='com_order_mapper',
            name='deliveryMethod',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
    ]
