# Generated by Django 2.2.11 on 2020-03-16 13:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sol', '0007_auto_20200303_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='com_order_mapper',
            name='autoRenewalFlag',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='com_order_mapper',
            name='initialTerm',
            field=models.IntegerField(blank=True, default=12),
        ),
        migrations.AddField(
            model_name='com_order_mapper',
            name='tfEligible',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='com_order_mapper',
            name='creationDate',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 16, 18, 37, 5, 679028)),
        ),
    ]
