# Generated by Django 2.2.11 on 2020-03-29 15:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sol', '0010_auto_20200329_2051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='com_order_mapper',
            name='renewalTerm',
        ),
        migrations.AlterField(
            model_name='com_order_mapper',
            name='creationDate',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 29, 21, 0, 24, 984575)),
        ),
    ]
